- name: Build Docker Image
  hosts: dockerservers
  gather_facts: false
  remote_user: ubuntu
  tasks:
    - name: Building Docker Image
      docker_image:
         name: test:latest
         source: build
         build:
            path: ~/test 
         state: present
         force_source: true
